### ISSUE TITLE
Aux arrays impromperly set with 3d amr

### ISSUE THREAD

**Issue by cjvogl** [clawpack/amrclaw#123]
Narrowed issue down to call to qad in advance.f.  Commenting out lines 217-220 in advance.f avoids the problem for now.

**Comment by cjvogl** [comment]
My mistake, the update to amrclaw from earlier today fixed this.

**Comment by mandli** [comment]
Did you mean to reopen this?

**Comment by cjvogl** [comment]
I did.  The particular code I was running will make a few steps now before the aux arrays are impromperly set (possibly during a regridding).  Those few initial steps had me fooled into thinking this was resolved and led me to close the issue when it does still exist.  Sorry for the confusion.

**Comment by mandli** [comment]
So the new fixes did not solve this?  Can you provide some examples of how this breaks and some output?

**Comment by cjvogl** [comment]
This was fixed/merged by @mjberger at while back and I just forgot to close it.
