### ISSUE TITLE
differences between amrclaw 5.0 and 4.x? 

### ISSUE THREAD

**Issue by donnaaboise** [clawpack/amrclaw#145]
I have written a shockbubble example in Clawpack 5.0, with the idea that I could compare the results to ForestCllaw.  But along the way, I realized that the solutions between 4.x and 5.0 versions differ quite a bit for this problem.  Forestclaw results compare quite nicely with the 4.3 version (not surprising, since I am using 4.x routines), but not at all with 5.0.  I am hoping there is something simple that might have changed between versions that could explain the difference.  I can update Forestclaw if needed. 

Here are three pictures showing the differences : 

![clawpack4 3](https://cloud.githubusercontent.com/assets/1406529/9514190/1146322a-4c55-11e5-8566-00d92a458ab2.png)

![clawpack5 0](https://cloud.githubusercontent.com/assets/1406529/9514192/13ba1c2e-4c55-11e5-869d-51babfd022e6.png)

![forestclaw](https://cloud.githubusercontent.com/assets/1406529/9514193/16dbbfa2-4c55-11e5-9680-32982e93f00c.png)

I realize this problem is very susceptible to small perturbations, but in fact, this is exactly why it is a good test of AMR schemes.  The AMR shouldn't be perturbing the solution in any significant way.  The fact that forestclaw and 4.3 produce such similar,results using very different adaptive schemes suggests that the AMR isn't perturbing the solution too much.  I think I've checked all the obvious sources of discrepency (limiters, order of accuracy, source terms, resolution, color axis, etc ...)  I also tried turing off the entropy fix, in case that what appears to be a newer version in 5.0 was affecting things.  

Any thoughts on what could be a possible source of difference would be very useful.    I can issue a PR for the shock-bubble example, if that would be helpful, or provide more general info on how I've set up the problem.

**Comment by mjberger** [comment]
We are currently looking into why that example is so different.  But for one thing, it has changed to use dimensional splitting, so you could put it back to the same method as the 4.3 (which I believe was the 22 method) and try again.

**Comment by mjberger** [comment]
oops - I just realized that I am looking at the 3d shock bubble problem, not 2d. I will take a look at it.

Marsha

**Comment by donnaaboise** [comment]
I figured out the problem - `gamma` and `gamma1` were set to 0 (or undefined) in `src2`.  the difference between a common block named `cparam` (from setprob) and `param` (from src2).   How would we spend our time if it weren't for common blocks?

4.3 and 5.0 are now virtually identical (in the eyeball norm) and agree with the original 4.3 results.
