### ISSUE TITLE
Whether a cell is covered by a patch with a grid of higher levels

### ISSUE THREAD

**Issue by xinshengqin** [clawpack/amrclaw#157]
Hi,

I am trying to plot data from clawpack in Paraview. I wrote a python code based on pyclaw to convert clawpack output data to VTK format (vtkOverlappingAMR), which can be read by Paraview. The prototype works well except for that sometimes Paraview will crash with "segmentation fault" occasionally. One reason for this might be because I didn't specify whether a cell has finer grid on top of it.

Does anybody know how I can tell, from clawpack output data, whether a cell (or a region) is covered by a patch with a grid of higher levels (Perhaps from pyclaw)? 

Thanks!

**Comment by mandli** [comment]
Unfortunately this is non-trivial.  You would have to check to see if the cell in question is covered by any grids in a higher level.  When plotting this we get away with not checking this by simply plotting the coarsest grids first and letting the higher levels cover it up.  Definitely not as efficient as it could be but cutting out the data on the coarser grids for overlapping regions seems more difficult.

Before you start trying to figure this out are you sure Paraview is crashing because of the data problem?  Seems like the name of the VTK format would imply this should work.

**Comment by mjberger** [comment]
It is possible that Donna did something like this for her 3D matlab graphics package?

Either before the files are output, or possibly as a post processing step, you would have to write code that loops over all grids and sticks a special value in if the cell is covered. I have used a “nan” for example.  This would be called by the “valout” routine presumably if done before outputting.

But as Kyle asks, doesn’t paraview (or for that matter VisIt) handle this internally for AMR grids?


 — Marsha

**Comment by donnacalhoun** [comment]
When doing the visualization in Matlab/GoogleEarth, I was able to mask out coarser regions by simply replacing these regions with NAN values (or something equivalent for matplotlib).   This meant that before plotting a single coarse grid, I scan all grids on all finer levels, and mask any region on the coarse grid that was covered by the finer grid.    This was relatively straightforward, although not terribly efficient.   This code is in visclaw/src/python/visclaw/frametools.py : 

if plotfigure.use_for_kml:

                        # -------------------------------------------------------------
                        # Mask out all coarse grid regions that are under fine grids
                        # This could be made into a subroutine
                        # -------------------------------------------------------------
                        this_level = patch.level

                        xc_centers,yc_centers = patch.grid.c_centers
                        mask_coarse = np.empty(xc_centers.shape, dtype=bool)
                        mask_coarse.fill(False)
	      .........


That said, I would have thought that the VTK ‘OverlappingAMR’ file format would handle this.  And from what you said, it sounds like it mostly works.  So I am not sure why you would need to do any masking yourself.  Do you have a special situation in mind?

**Comment by xinshengqin** [comment]
I used the standard VTK library to write a VTK file with the vtkOverlappingAMR class in that library. (See https://github.com/xinshengqin/claw_to_vtk/tree/master/standard_vtk_data)

For example, in https://github.com/xinshengqin/claw_to_vtk/blob/master/standard_vtk_data/my_Gaussian2D/my_Gaussian2D_0.vti, the dataArray element with name "vtkGhostType" specifies which cell is covered by grids of higher levels (8 marks it as being covered and 0 marks it as not being covered). This makes us able to specify which level we would like to show data on in Paraview (For example, see https://github.com/xinshengqin/claw_to_vtk/blob/master/standard_vtk_data/showing_first_two_levels.png)

My Python script reads in Clawpack data and writes data in such a VTK format but does not write "vtkGhostType" element.

I am not 100% sure this is what causes Paraview to crash but this is the last thing I haven't tried on my list.

**Comment by mandli** [comment]
So in order for this to work you do have to explicitly mark the cells as being overlapped, that's unfortunate.  I wonder if the problem then really is that you are missing some of these marks?

**Comment by xinshengqin** [comment]
Thank you all.
I think perhaps I should proceed in this direction at this moment (marking overlapped cells to let Paraview know) with the approach pointed out by Marsha, before I can come up with other things to explore.

**Comment by xinshengqin** [comment]
Recently I modified my code such that it can tell which cell is covered by finer grids and write that information into the VTK file as well. I believe this makes the VTK file that my code produces exactly follows the format of standard VTK. But Paraview still crash occasionally. You may successfully read the same VTK file in Paraview and plot as you want for 5 times and fail for once (Paraview just crashed).

**Comment by xinshengqin** [comment]
BTW, someone wrote a reader in VisIt for GeoClaw. So actually we can directly read GeoClaw _output into VisIt. But I found that VisIt has similar problem: it occasionally failed to read in the data and reported error.

**Comment by mandli** [comment]
> Recently I modified my code such that it can tell which cell is covered by finer grids and write that information into the VTK file as well. I believe this makes the VTK file that my code produces exactly follows the format of standard VTK. But Paraview still crash occasionally. You may successfully read the same VTK file in Paraview and plot as you want for 5 times and fail for once (Paraview just crashed).

I know Paraview is a bit temperamental sometimes but this sounds like a bug.  Have you tried reaching out to their mailing list at all and see if you can gain an idea of what be going wrong?

> BTW, someone wrote a reader in VisIt for GeoClaw. So actually we can directly read GeoClaw _output into VisIt. But I found that VisIt has similar problem: it occasionally failed to read in the data and reported error.

Interesting, I know there was a plugin for Clawpack in general awhile ago in VisIt but it had not been updated in a long time.

**Comment by xinshengqin** [comment]
That's a good idea. At this time the best choice might be to send an email to their mailing list. Thanks!
