### ISSUE TITLE
auto clean-up for nosetests

### ISSUE THREAD

**Issue by xinshengqin** [clawpack/amrclaw#196]
After run, say,  nosetests acoustics_2d_radial, *.o files are created in ./acoustics_2d_radial

Next time you run nosetests acoustics_2d_radial again, those *.o files won't be cleaned up but will be reused instead. This might cause some issues when you have changed source *.f90 files in, say, amrclaw/src/2d or switch to another compiler, and then run all the tests. For now I think we have to clean up *.o files in each tests by ourselves?

It would be nice if the test script can do this?

**Comment by mandli** [comment]
Originally there was a line in the `__init__.py` files in each test subdirectory that effectively did a `make clean` but I think we pulled that as there were some unintended side-effects while doing that.  We could easily add something similar to the particular `__init__.py` files that would either remove only the local object files or do a `make clean` every time although that would significantly increase the test times.

**Comment by xinshengqin** [comment]
I see. Thanks!
For now I will just use a bash script to do the clean up "semi"-automatically.

**Comment by mandli** [comment]
I am not sure if this should be closed, we should probably leave it open until we find a robust way of taking care of this.

**Comment by xinshengqin** [comment]
Sorry I thought you meant I should do it by myself because of the side effects. 

I am not very confident on making changes to this part of the code since I don't know what the side effects can be.

**Comment by mandli** [comment]
Nothing like diving into the unknown :)

I think at least in this case that a couple of system commands from `__init__.py` should do the trick.  Basically just reuse your bash script.  We can open a more general issue about looking into this.

**Comment by xinshengqin** [comment]
For now my bash script looks like:
#!/bin/bash

regex="*_output"
for i in $(ls);
do
    if [[ ${i} == ${regex} ]] 
    then
        # clean up previous output files
        echo "remove ${i}"
        rm -r ${i}
    elif [[ -d ${i} ]]
    then
        # clean up previously compiled *.o and *.mod files
        echo "clean up ${i}..."
        cd ${i} && make clobber && cd ..
    fi
done

**Comment by mandli** [comment]
Is this a general script for cleaning up examples?  `make clobber` will get rid of at least `_output`.  In any case the equivalent in Python would be something like
```python
import glob
import shutil
import subprocess

output_paths = glob.glob("*_output")
for path in output_paths:
    shutil.rmtree(path)
subprocess.call('make clobber', shell=True)
```

**Comment by xinshengqin** [comment]
In my script, the first branch of the if statement is not for cleaning up _output files in say, /tests/acoustics_2d_radial. It's for cleaning up output files in /tests, which is produced by previous test if any of them failed.

Thank you for the python code, I will try them soon.

**Comment by mandli** [comment]
Actually, if that's your goal then doing some variant of `git clean` will get rid of any non-tracked files.  Also those `*_output` directories should be copied to wherever you ran the tests from so not necessarily in the `tests` directory.

**Comment by xinshengqin** [comment]
I see. Just learned how to use nosetest so didn't think of that. :)

**Comment by mandli** [comment]
I still think it might be worthwhile doing something in the `__init__.py` to remove those extra object files though.  You could just hard-code it in the file given we know what they are called.

**Comment by xinshengqin** [comment]
Should I change that, test it and raise a pull request?

**Comment by mandli** [comment]
Perfect.

**Comment by xinshengqin** [comment]
output_paths = glob.glob("*_output")
for path in output_paths:
    shutil.rmtree(path)

is for removing output from previous failed tests, right?
However, in tearDown() of the unitest, it will always check whether *_output exists and remove it if so. So if I put this clean-up code before/in setting up the unitest, there is no need to check whether *_output exists in tearDown() since *_output has been removed before/in setting up the unitest.

**Comment by xinshengqin** [comment]
![image](https://cloud.githubusercontent.com/assets/10212680/26238094/72f0c6de-3c2c-11e7-81ad-e7923554d05f.png)

**Comment by xinshengqin** [comment]
I add the code to "make clobber" in ClawpackRegressionTest.setup() instead of __init__.py. 
My thought is to put the code for removing *_output of corresponding test here as well.
Any thoughts?

**Comment by mandli** [comment]
This would require recompilation of all the source every time a test is run which would lead to unneeded recompilation.  What we would really want is to clean up only the local source.  We could add a rule into all of the tests that gets called to clean up the local source.  That I think would be the ideal implementation.

**Comment by xinshengqin** [comment]
Did you mean what "make clean" does?

When I raise this issue, I was also talking about *.o files in, say amrclaw/src/2d. This issue came from switching compiler from one to another and the local (new compiled) *.o may not be compatible with previous compiled *.o in amrclaw/src/2d. In this case, if you run a test and it recompiled local source, it would failed since it cannot link local *.o with *.o in amrclaw/src/2d.

**Comment by xinshengqin** [comment]
It would be idea if we also compile everything to source in a temporary directory as what we did for output during the test and clean that up? But our Makefile does not really handle this, right?

**Comment by mandli** [comment]
That's correct.  I finally remembered where we clean out the object files, it's at `src/python/amrclaw/test.py`.  You could add some lines there that would clean out the `*.o` files from the test directories (as well as the `*.mod` files).

The reason we do not build in each of the temporary directories is that we would need to again rebuild all the object files for each test case.  We could in principle get around this but it would require some nosetest magic.

**Comment by xinshengqin** [comment]
A brief summary:
1. all *.o file in amrclaw/src/2d and amrclaw/src/3d get cleaned up in src/python/amrclaw/test.py before each tests.
2. *.o files in other src, e.g. riemann/src, are not removed.
3. *.o files in test directory, e.g. amrclaw/tests/acoustics_2d_radial, are not removed.
4. All output files and the executable, xamr, during the tests are put in temporary path.



So why do we still need to do "make clean" in test directory? I didn't see any change "make clean" will make to the test directory. 
I raised this issue since I think doing item 3 above before each test make sense. 
I don't know why we don't do item 2 while we do item 1 above...?

**Comment by xinshengqin** [comment]
I raised a pull request at clawpack/amrclaw/#120, which makes showing the code easier.

**Comment by mandli** [comment]
> So why do we still need to do "make clean" in test directory? I didn't see any change "make clean" will make to the test directory.

`make clean` would also remove the files you mentioned in 3.

> I raised this issue since I think doing item 3 above before each test make sense.

Agreed.

> I don't know why we don't do item 2 while we do item 1 above...?

This is harder to do as it's test dependent.  If we did call out to the Makefile instead we could do something but there's really no way to do this directly.  We could also remove all the Riemann solver `*.o` files but we would have to be a bit careful so as to remove what needs to be removed and not other compiled objects.

**Comment by xinshengqin** [comment]
When I type "make clean" in a case directory, I didn't see it removed *.o files in that case directory? 
![image](https://cloud.githubusercontent.com/assets/10212680/26279367/bbb1acfe-3d66-11e7-8d2b-08392c859054.png)

**Comment by xinshengqin** [comment]
For item 2 I put several codes in src/python/amrclaw/test.py before but since you mentioned there might be other issues I will just get rid of this.
![image](https://cloud.githubusercontent.com/assets/10212680/26279440/ca44d050-3d68-11e7-91f9-37dc40135c1b.png)

**Comment by mandli** [comment]
Maybe only `make clobber` gets rid of object files (I don't generally use `make clean` or `make clobber`).  I think placing a special rule in the makefiles that could be called for the tests specifically may still be a better way to implement what we want.

**Comment by xinshengqin** [comment]
So the original code in src/python/amrclaw/test.py is to clean up *.o files in amrclaw/src/2d and amrclaw/src/3d, which forces the re-compilation every time we run tests. If I add code there to clean up all other *.o files, which is essentially what make clobber will do.

But I think the difference between putting clean-up code in src/python/amrclaw/test.py and doing "make clobber" or similar alternatives specifically for tests case is: 
If you run  "nosetests tests" in $CLAW/amrclaw, the former design will clean up once, recompile once and run tests for all 5 tests in amrclaw/tests. However, the later one will clean up *.o files 5 times and recompile 5 times, which, as I understand, is what you would like to avoid as you mentioned above.

**Comment by mandli** [comment]
Exactly.
