### ISSUE TITLE
Can't compile in example case but can do that in src

### ISSUE THREAD

**Issue by xinshengqin** [clawpack/amrclaw#197]
I built a new fortran module in src/2d, which contains something like
**module stepgrid_module
    implicit none
    double precision, public :: dtcom,dxcom,dycom,tcom
    integer, public :: icom,jcom
    ...**
and in step2.f90 I have something like 
**use stepgrid_cuda_module, only: dtcom,dxcom,dycom,tcom,icom,jcom**

Doing make .exe in a an example case will stoped at 
**"gfortran -c /home/xsqin/clawpack/amrclaw/src/2d/step2.f90 -I/home/xsqin/clawpack/amrclaw/src/2d/ -I/home/xsqin/clawpack/classic/src/ -L/home/xsqin/clawpack/amrclaw/examples/acoustics_2d_radial/    -o /home/xsqin/clawpack/amrclaw/src/2d/step2.o"** and says something like 
**"Illegal use of symbol jcom - not public entity of module"** for all these variables.

However, if I execute the same compile command:
**"gfortran -c /home/xsqin/clawpack/amrclaw/src/2d/step2.f90 -I/home/xsqin/clawpack/amrclaw/src/2d/ -I/home/xsqin/clawpack/classic/src/ -L/home/xsqin/clawpack/amrclaw/examples/acoustics_2d_radial/    -o /home/xsqin/clawpack/amrclaw/src/2d/step2.o"**
in $CLAW/amrclaw/src/2d, it just compiled...

This is really weird to me. Can't find anything helpful on the internet... Any ideas?

**Comment by mandli** [comment]
A couple of thoughts:
1. The order of compilation is very important here, you need to compile the module before it's used in any other source.
1. Is the the name of the module correct?  It looks like there's a discrepency above.

**Comment by xinshengqin** [comment]
1. I removed "cuda" in the module name here to avoid confusion since there isn't any cuda code inside yet. So they are consistent.
2. I first did "make .exe" which got stuck when compile step2.f90 to step2.o for the reason above. Then I copied exactly the same compile command to execute in src/2d and it worked. Then I copied the same compile command to execute in acoustic_2d_radial/ and it failed for the same reason above...

So weird... 

BTW, actually the error message above is from pgfortran, which is a fortran compiler from PGI. If I use gfortran, it said stepgrid_cuda_module.mod is not a gfortran module if I execute the compile command in acoustic_2d_radial/, but succeeded if I execute it in src/2d ...

**Comment by xinshengqin** [comment]
I have tested pgfortran with master branch and everything works fine.  So I should be using the new compiler in a correct way. Also both compiler failed under the same circumstance and succeed under another same circumstance.

**Comment by mandli** [comment]
Did you add the module to the Makefile then?

**Comment by xinshengqin** [comment]
Yes, in Makefile.amr_2d I have
COMMON_MODULES += \
  $(CLAW)/classic/src/utility_module.f90 \
  $(AMRLIB)/amr_module.f90 \
  $(AMRLIB)/gauges_module.f90 \
  $(AMRLIB)/regions_module.f90 \
  $(AMRLIB)/stepgrid_cuda_module.f90

**Comment by xinshengqin** [comment]
It did compile stepgrid_cuda_module.f90 to stepgrid_cuda_module.o and stepgrid_cuda_module.mod in src/2d. That's why I am able to compile step2.f90 to step2.o, but only if I execute the compile command in src/2d, not in example case...

**Comment by mandli** [comment]
We really do not handle the case when the module and source file names don't match although I am not sure that's the problem.  Have you tried modifying the local Makefile rather than the one in the src directory?

**Comment by xinshengqin** [comment]
Just solved this by checkout an old commit and re-write the codes I need. 
Although I am still not sure what caused the problem but since it went away I can close this now.
