### ISSUE TITLE
Remove Unset Timing Variables From 3D

### ISSUE THREAD

**Issue by mandli** [clawpack/amrclaw#208]
They appear to have not been removed when we did this for 2D.  This is a problem as the intel compiler when told to be thorough complains about these variables.  For instance in `ginit.f` was have
```fortran
         timeSetaux = timeSetaux + clock_finish - clock_start
         timeSetauxCPU = timeSetauxCPU + cpu_finish -cpu_start
```
which the run-time checks then complain about.

**Comment by mandli** [comment]
Can I just remove these?  I have a test case that fails because of this bug.

**Comment by rjleveque** [comment]
This seems to be fixed.
